### ISSUE TITLE
bridesmaid schedule

### ISSUE THREAD

**Issue by dudasaus** [stewabro/brukes-wedding#2]
I think they need to start at 7am tbh

attached is pic of Calvin at 7am

![C749D1A6-36EC-4D33-A52B-FF54A2FD1989](https://user-images.githubusercontent.com/15874019/170390787-898b7017-8415-4ae8-946b-158b1b400fa5.jpeg)

**Comment by stewabro** [comment]
We've carefully reviewed your issue and are closing it with the following explanation:

_No_

Thank you for your contribution. (Hi Cal <3)
